[2023-01-05T11:33:10.851+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: UK_Accidents_pipeline.create_dashboard_task manual__2023-01-05T10:53:41.626541+00:00 [queued]>
[2023-01-05T11:33:10.863+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: UK_Accidents_pipeline.create_dashboard_task manual__2023-01-05T10:53:41.626541+00:00 [queued]>
[2023-01-05T11:33:10.864+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-05T11:33:10.864+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-01-05T11:33:10.885+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-05T11:33:10.988+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): create_dashboard_task> on 2023-01-05 10:53:41.626541+00:00
[2023-01-05T11:33:11.004+0000] {standard_task_runner.py:55} INFO - Started process 3265 to run task
[2023-01-05T11:33:11.012+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'UK_Accidents_pipeline', 'create_dashboard_task', 'manual__2023-01-05T10:53:41.626541+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/UK_Accidents.py', '--cfg-path', '/tmp/tmps1256nxr']
[2023-01-05T11:33:11.017+0000] {standard_task_runner.py:83} INFO - Job 99: Subtask create_dashboard_task
[2023-01-05T11:33:11.230+0000] {task_command.py:389} INFO - Running <TaskInstance: UK_Accidents_pipeline.create_dashboard_task manual__2023-01-05T10:53:41.626541+00:00 [running]> on host 5c8dbd0ba0f2
[2023-01-05T11:33:11.697+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=UK_Accidents_pipeline
AIRFLOW_CTX_TASK_ID=create_dashboard_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-05T10:53:41.626541+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-05T10:53:41.626541+00:00
[2023-01-05T11:33:18.929+0000] {logging_mixin.py:137} WARNING - /opt/***/dags/UK_Accidents.py:40 DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
[2023-01-05T11:33:42.797+0000] {logging_mixin.py:137} INFO - Dash is running on http://0.0.0.0:8050/
[2023-01-05T11:33:42.797+0000] {dash.py:1968} INFO - Dash is running on http://0.0.0.0:8050/

[2023-01-05T11:33:43.651+0000] {logging_mixin.py:137} INFO -  * Serving Flask app '***'
[2023-01-05T11:33:43.652+0000] {logging_mixin.py:137} INFO -  * Debug mode: off
[2023-01-05T11:33:43.654+0000] {_internal.py:224} INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8050
 * Running on http://172.18.0.4:8050
[2023-01-05T11:33:43.654+0000] {_internal.py:224} INFO - [33mPress CTRL+C to quit[0m
[2023-01-05T11:34:06.598+0000] {_internal.py:224} INFO - 172.18.0.1 - - [05/Jan/2023 11:34:06] "GET / HTTP/1.1" 200 -
[2023-01-05T11:34:08.346+0000] {_internal.py:224} INFO - 172.18.0.1 - - [05/Jan/2023 11:34:08] "GET /_dash-component-suites/dash/deps/react@16.v2_7_1m1672594001.14.0.min.js HTTP/1.1" 200 -
[2023-01-05T11:34:08.397+0000] {_internal.py:224} INFO - 172.18.0.1 - - [05/Jan/2023 11:34:08] "GET /_dash-component-suites/dash/deps/prop-types@15.v2_7_1m1672594001.8.1.min.js HTTP/1.1" 200 -
[2023-01-05T11:34:08.399+0000] {_internal.py:224} INFO - 172.18.0.1 - - [05/Jan/2023 11:34:08] "GET /_dash-component-suites/dash/deps/polyfill@7.v2_7_1m1672594001.12.1.min.js HTTP/1.1" 200 -
[2023-01-05T11:34:08.401+0000] {_internal.py:224} INFO - 172.18.0.1 - - [05/Jan/2023 11:34:08] "GET /_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_7_1m1672594001.min.js HTTP/1.1" 200 -
[2023-01-05T11:34:08.404+0000] {_internal.py:224} INFO - 172.18.0.1 - - [05/Jan/2023 11:34:08] "GET /_dash-component-suites/dash/dash_table/bundle.v5_2_1m1672594001.js HTTP/1.1" 200 -
[2023-01-05T11:34:08.446+0000] {_internal.py:224} INFO - 172.18.0.1 - - [05/Jan/2023 11:34:08] "GET /_dash-component-suites/dash/dcc/dash_core_components-shared.v2_7_1m1672594001.js HTTP/1.1" 200 -
[2023-01-05T11:34:08.448+0000] {_internal.py:224} INFO - 172.18.0.1 - - [05/Jan/2023 11:34:08] "GET /_dash-component-suites/dash/deps/react-dom@16.v2_7_1m1672594001.14.0.min.js HTTP/1.1" 200 -
[2023-01-05T11:34:08.668+0000] {_internal.py:224} INFO - 172.18.0.1 - - [05/Jan/2023 11:34:08] "GET /_dash-component-suites/dash/html/dash_html_components.v2_0_7m1672594002.min.js HTTP/1.1" 200 -
[2023-01-05T11:34:09.448+0000] {_internal.py:224} INFO - 172.18.0.1 - - [05/Jan/2023 11:34:09] "GET /_dash-dependencies HTTP/1.1" 200 -
[2023-01-05T11:34:09.613+0000] {_internal.py:224} INFO - 172.18.0.1 - - [05/Jan/2023 11:34:09] "GET /_favicon.ico?v=2.7.1 HTTP/1.1" 200 -
[2023-01-05T11:34:10.627+0000] {_internal.py:224} INFO - 172.18.0.1 - - [05/Jan/2023 11:34:10] "GET /_dash-layout HTTP/1.1" 200 -
[2023-01-05T11:34:12.786+0000] {_internal.py:224} INFO - 172.18.0.1 - - [05/Jan/2023 11:34:12] "GET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1" 200 -
[2023-01-05T11:34:14.148+0000] {_internal.py:224} INFO - 172.18.0.1 - - [05/Jan/2023 11:34:14] "[36mGET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1[0m" 304 -
[2023-01-05T11:34:57.284+0000] {local_task_job.py:82} ERROR - Received SIGTERM. Terminating subprocesses
[2023-01-05T11:34:57.931+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 3265. PIDs of all processes in the group: [3265]
[2023-01-05T11:34:58.714+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 3265
[2023-01-05T11:34:58.896+0000] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-01-05T11:34:59.248+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/UK_Accidents.py", line 40, in create_dashboard
    CreateDash(filename)
  File "/opt/airflow/dags/dashboard.py", line 96, in CreateDash
    app.run_server(host ='0.0.0.0',debug=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/dash/dash.py", line 2133, in run_server
    self.run(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/dash/dash.py", line 1980, in run
    self.server.run(host=host, port=port, debug=debug, **flask_run_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/flask/app.py", line 1188, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/home/airflow/.local/lib/python3.7/site-packages/werkzeug/serving.py", line 1098, in run_simple
    srv.serve_forever()
  File "/home/airflow/.local/lib/python3.7/site-packages/werkzeug/serving.py", line 741, in serve_forever
    super().serve_forever(poll_interval=poll_interval)
  File "/usr/local/lib/python3.7/socketserver.py", line 232, in serve_forever
    ready = selector.select(poll_interval)
  File "/usr/local/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1485, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-01-05T11:35:04.712+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=UK_Accidents_pipeline, task_id=create_dashboard_task, execution_date=20230105T105341, start_date=20230105T113310, end_date=20230105T113504
[2023-01-05T11:35:05.565+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 99 for task create_dashboard_task (Task received SIGTERM signal; 3265)
[2023-01-05T11:35:05.646+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=3265, status='terminated', exitcode=1, started='11:33:10') (3265) terminated with exit code 1
[2023-01-05T11:35:05.647+0000] {local_task_job.py:159} INFO - Task exited with return code 143
[2023-01-05T11:35:05.663+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
